#!/bin/bash

case $1 in
	-*)
		echo "Usage:"
		echo "	$0 [module]"
		exit -1;
		;;
esac

MODULE=$1
for path in /bin /usr/bin /usr/local/bin ; do
	if [ -f "$path/sed" ] ; then
		SED="$path/sed"
	fi
	if [ -f "$path/xargs" ] ; then
		XARGS="$path/xargs"
	fi
	if [ -f "$path/git" ] ; then
		GIT="$path/git"
	fi
	if [ -f "$path/cvs" ] ; then
		CVS="$path/cvs"
	fi
done

if [ -z "$GIT" ]; then
	echo "$0: no git installation found"
	exit 1
fi

if [ -z "$CVS" ]; then
	echo "$0: no cvs installation found"
	exit 1
fi


if [ -z "$MODULE" ]; then
	echo "$0: no CVS module declared"
	exit 1
fi

if [ -z "$CVSROOT" ]; then
	echo "$0: CVSROOT not set"
	exit 1
fi

if [ ! -d "$HOME/cvs/$MODULE" ]; then
	cd $HOME/cvs
	$CVS -d $CVSROOT co $MODULE
fi

cd $HOME/git
unset GIT_DIR
$GIT cvsimport -v -i -k -a -d $CVSROOT -r cvs -C ${MODULE}_cvs $MODULE
cd $HOME/git/${MODULE}_cvs
$GIT update-ref HEAD refs/remotes/cvs/master

if [ ! -d "$HOME/git/$MODULE" ]; then
	cd $HOME/git
	$GIT clone -l -o cvs ${MODULE}_cvs $MODULE
fi

cd $HOME/git/${MODULE}

STASH=$( $GIT ls-files -cdmskut --directory )
if [ -n "$STASH" ]; then
	$GIT stash save 'pre cvs2git'
fi

$GIT fetch
$GIT pull cvs master
$GIT reset --hard cvs/master
if [ -n "$STASH" ]; then
	$GIT stash pop
fi
