#!/bin/bash

SED=/bin/sed
XARGS=/usr/bin/xargs
CVS=/usr/bin/cvs
GIT=/usr/local/bin/git

MODULE=$1

if [ -z "$MODULE" ]; then
	echo "$0: no CVS module declared"
	exit 1
fi

cd $HOME/cvs/$MODULE
$CVS up
if [ 0 != $? ]; then
	exit $?
fi

export GIT_DIR=$HOME/git/$MODULE/.git
$GIT cherry cvs/master master | $SED 's/^+ //' | $XARGS -l1 $GIT cvsexportcommit -c -p -v
