#!/bin/bash

case $1 in
	-*)
		echo "Usage:"
		echo "	$0 [module]"
		exit -1;
		;;
esac

MODULE=$1

for path in /bin /usr/bin /usr/local/bin ; do
	if [ -f "$path/sed" ] ; then
		SED="$path/sed"
	fi
	if [ -f "$path/xargs" ] ; then
		XARGS="$path/xargs"
	fi
	if [ -f "$path/git" ] ; then
		GIT="$path/git"
	fi
	if [ -f "$path/cvs" ] ; then
		CVS="$path/cvs"
	fi
done

if [ -z "$GIT" ]; then
	echo "$0: no git installation found"
	exit 1
fi

if [ -z "$CVS" ]; then
	echo "$0: no cvs installation found"
	exit 1
fi

if [ -z "$MODULE" ]; then
	echo "$0: no CVS module declared"
	exit 1
fi

cd $HOME/cvs/$MODULE
$CVS up -dP
if [ 0 != $? ]; then
	exit $?
fi

export GIT_DIR=$HOME/git/$MODULE/.git
$GIT cherry cvs/master master | $SED 's/^+ //' | $XARGS -l1 $GIT cvsexportcommit -c -p -v
